version: '3'

services:
  nodegreen:
    build: .
    ports:
      - '8001:3000'
    container_name: nodegreen
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /aws/ec2/server-dev
        awslogs-stream: apilogs
        awslogs-datetime-format: \%Y-%m-%d %H:%M:%S\]
        tag: "{{.Name}}-{{.ID}}"
    environment:
      - PORT=3000
      - CONTAINER_NAME=nodegreen
    restart: unless-stopped
